### ISSUE TITLE
azurespeed.com is not working in IE8

### ISSUE THREAD

**Issue by avi081265** [blrchen/AzureSpeed#2]
Hello

I try to run azurespeed.com  site on IE 8 browser on Windows 2008 platform. I am getting jQuery error.

Please advise

Avian

**Comment by blrchen** [comment]
Thank you for your feedback. I think it's expected as jQuery 2.x drops IE8 support. Not sure if the fix is as easy as just downgrade jQuery to latest 1.x.

**Comment by blrchen** [comment]
Close as by design as latest jQuery/AngularJS removes IE8 support.
