### ISSUE TITLE
Add german regions

### ISSUE THREAD

**Issue by Tevion** [blrchen/AzureSpeed#21]
Please add the two german datacenters.

https://azure.microsoft.com/en-us/blog/microsoft-azure-germany-now-available-via-first-of-its-kind-cloud-for-europe/

**Comment by blrchen** [comment]
Thanks for your feedback unfortunately I do not have account for German so can't add this now. German, China, Fairfax uses different accounts than global azure.

**Comment by sunkibaek** [comment]
@blrchen How about South Korea? They have just opened regions here. Wonder how latency compares to other regions. Thanks!

**Comment by gitralf** [comment]
Maybe I can help you with a test account for germany. please contact me and let's see what I can do...

**Comment by blrchen** [comment]
@sunkibaek thanks for letting me know, 2 Korea regions are added.

**Comment by sunkibaek** [comment]
great thanks! i will check it out.

**Comment by rawi-saas** [comment]
Hey. Any news on the German datacenters?

**Comment by iNgeon** [comment]
> 
> 
> @sunkibaek thanks for letting me know, 2 Korea regions are added.

Since there was a small side track... I noticed some regions dissapeared, as example South Africa gone and only UAE show under Africa and middle East https://azure.microsoft.com/en-us/global-infrastructure/regions/

**Comment by blrchen** [comment]
Hello, new Germany regions ( Germany North & Germany West Central ) are added, please give a try
