### ISSUE TITLE
Replace StyleCop.MSBuild

### ISSUE THREAD

**Issue by blrchen** [blrchen/AzureSpeed#44]
Need to find an alternative as StyleCop.MSBuild does not work well with dotnet core projects.

**Comment by blrchen** [comment]
StyleCop.MSBuild is removed in order to make dotnet build work. Seems there is an open issue https://github.com/StyleCop/StyleCop/issues/126 tracked in StyleCop.MSBuild

**Comment by dvm-2k1** [comment]
@blrchen, please let me know how you fixed/removed StyleCop.MSBuild from the projects... I'm having same issue when I'm trying to build our ASP.Net Core 2.0 projects with "dotnet build" command.

**Comment by blrchen** [comment]
Find a good StyleCop.MSBuild replacement: StyleCop.Analyzers. It works well so far
