### ISSUE TITLE
High ping

### ISSUE THREAD

**Issue by Muhannad518** [blrchen/AzureSpeed#56]
I have been facing problem with ping lately. I used to get about 100ms in EU servers, but now i'm getting +220ms. Just in Azure servers, in which Rainbow Six Siege run their servers as far as i know.
My ping in other games is too good, so please fix this issue as fast as you can.
![eu](https://user-images.githubusercontent.com/31934558/30393420-ba0ec07c-98c8-11e7-8949-5de8b1179072.jpg)

**Comment by Muhannad518** [comment]
The problem has been solved, I hope it doesn't come back later like before

**Comment by blrchen** [comment]
Closing as this issue is related to Rainbow Six Siege or Azure
