### ISSUE TITLE
Different performance in different browsers

### ISSUE THREAD

**Issue by ShadowXVII** [blrchen/AzureSpeed#6]
There is a noticeable difference between say IE and CHrome. Incidentally, IE is getting better ping results than Chrome. 

e.g. my Chrome gives 1000ms for a local data center, but 50ms in IE.
I've seen different results across computers as well. 

Looking at the [timings on IE vs. Chrome](https://imgur.com/a/N7C7d) (note that these results are not necessarily for the same server, but are similar between all requests), it seems Chrome is stalling before the XHR request more than IE. I'm not sure what the measure is for the website (whether it's round trip, or just waiting time) but perhaps Chrome is simply throttling the # of simultaneous XHR requests?

I can see that there is already a random number on the end of the string -- perhaps [Chrome is still stalling to see the response of other XHRs](http://stackoverflow.com/questions/27513994/chrome-stalls-when-making-multiple-requests-to-same-resource) before continuing?

Similar issue reported here: [https://github.com/two10degrees/AzureSpeedTest/issues/6](https://github.com/two10degrees/AzureSpeedTest/issues/6)

**Comment by blrchen** [comment]
I don't have a fix for this issue. I am thinking to add an option dialog allow user select interested regions/data centers, this might reduce the chance XHR requests get throttled by Chrome.

But for those who select all region data centers to run speed test, they will continue to experience this unless someone knows a real fix for this.

**Comment by blrchen** [comment]
I added a region selector in each speed test page, This allows users only selected datacenters they are interested to know latency, instead of testing directly to all (34) data centers. Hopefully this can reduce the chance for requests to get throtted
