### ISSUE TITLE
France Central/South Regions

### ISSUE THREAD

**Issue by alaatm** [blrchen/AzureSpeed#61]
It would be great to add these 2 new regions.

**Comment by andreujuanc** [comment]
Need this

**Comment by blrchen** [comment]
Hello @alaatm and @andreujuanc , thanks for raising this issue.

France Central is added

I do not have access to France South so I can not add it, all speed tests require storage account created in target region with configurations.

**Comment by andreujuanc** [comment]
Nice! Thanks!!
