### ISSUE TITLE
Lines at the top of Datacenter IP range need re-wording.

### ISSUE THREAD

**Issue by BradDennis** [blrchen/AzureSpeed#62]
The sentence at the top of the Datacenter IP Range needs to be re-worked.

Datacenter IP Range
Some funny data for how many public ip address do Microsoft, AWS and Alibaba owns. If you know ip or url, you can use Cloud Region Finder to find our detail cloud and region info

**Comment by blrchen** [comment]
Thanks for your feedback, wordings are refined
