### ISSUE TITLE
Add Australia Central datacenters

### ISSUE THREAD

**Issue by jamesbannan** [blrchen/AzureSpeed#63]
Please add the two new Australian datacenters: Australia Central and Australia Central 2

```
{
    "displayName": "Australia Central",
    "id": "/subscriptions/xxx/locations/australiacentral",
    "latitude": "-35.3075",
    "longitude": "149.1244",
    "name": "australiacentral",
    "subscriptionId": null
  },
  {
    "displayName": "Australia Central 2",
    "id": "/subscriptions/xxx/locations/australiacentral2",
    "latitude": "-35.3075",
    "longitude": "149.1244",
    "name": "australiacentral2",
    "subscriptionId": null
  }
```

**Comment by blrchen** [comment]
Hello @jamesbannan thanks for the feature request, but I can not enable latency test for these two Australian regions as I do not have access. These regions do not show up in my azure portal.

**Comment by blrchen** [comment]
Both Australia Central & Australia Central 2 are added, please give a try
