### ISSUE TITLE
Internet Explorer 11 (IE11) - "Download Speed Test" - JS Error: TypeError: Object doesn't support property or method 'find'

### ISSUE THREAD

**Issue by chrisjacob** [blrchen/AzureSpeed#65]
Steps:
1. Open IE 11
2. Go to: http://www.azurespeed.com/Azure/Download
3. Fails to display any download options
4. Open F12 Developer Tools, reload the page, and in console see JS Error: "TypeError: Object doesn't support property or method 'find'"... this is preventing the download page from working in IE11.

Note: The Latency and Upload pages are working fine in IE11. 
Note 2: The Download page is working fine in MS Edge.

**Comment by blrchen** [comment]
Thanks for reporting this issue, this has been fixed.

![image](https://user-images.githubusercontent.com/1607381/54607746-19c82480-4a8a-11e9-941b-cb9adb8e755a.png)
