### ISSUE TITLE
Are there plans to support tests against the Brazil (Brasil) data center too?

### ISSUE THREAD

**Issue by KarlZ** [blrchen/AzureSpeed#67]
I'm trying to figure out the best data center for someone that needs to connect from Cape Town, South Africa. On the maps it looks like Brazil might be a good choice? But I don't see that one listed.

**Comment by KarlZ** [comment]
My bad... Brazil South is listed... New Request... Can we call it "Americas" rather than "America"?

**Comment by blrchen** [comment]
Thanks for suggestions. I have changed all geography names to align with official [Azure geographies](https://azure.microsoft.com/en-us/global-infrastructure/geographies/)
