### ISSUE TITLE
Request: private connections via ExpressRoute

### ISSUE THREAD

**Issue by rutgerterhoeven** [blrchen/AzureSpeed#69]
Hi! Would it be feasible to show latency numbers via ExpressRoute (https://azure.microsoft.com/en-us/services/expressroute/) private connectivity vs. the public internet to test performance difference? Thanks, Rutger

**Comment by blrchen** [comment]
Sorry, this is something that currently not supported. Please try to setup the infrastructure within your own Azure subscription and test from there.

I will close this one as won't support
