### ISSUE TITLE
Why Do i have 180 to UAE North Datacenters and 80 Ping to EU France Datacenter, Im from israel, Which doesnt make any sence Because im closer to the UAE then EU ?

### ISSUE THREAD

**Issue by CubiTub** [blrchen/AzureSpeed#75]
Help Please? 
Doesnt make sence . Im closer to UAE servers then EU servers
So why do i get higher ping on UAE servers

**Comment by blrchen** [comment]
If you perform a download speed test on page http://www.azurespeed.com/Azure/Download, will you get similar result?

The latency are measured by performing small file (few bytes) download from your location to azure regions. If you believe you should get less latency when accessing UAE North datacenters, you should open an Azure support ticket to have someone engaged. 

The latency data depends on ISP too. My experience different ISPs in same city might use different upstream routes which results in different results.
