### ISSUE TITLE
Region disappeared

### ISSUE THREAD

**Issue by iNgeon** [blrchen/AzureSpeed#76]
I noticed some regions disappeared, as example South Africa gone and only UAE show under Middle East and Africa. Perhaps after China got added ?

https://azure.microsoft.com/en-us/global-infrastructure/regions/

Ps. Side note for some reason the trend graph only works for me in Google Chrome and not in Firefox (both latest versions) Although even randomly changing the areas do not update the graph as previously...

**Comment by blrchen** [comment]
Thanks for reporting the issue, South Africa was removed by mistake, it has been fixed.

Sorry I do not have bandwidth to fix the firefox issue. Could you please use Chrome as workaround?
