### ISSUE TITLE
FEATURE: Adjustable scale for latency test

### ISSUE THREAD

**Issue by softwarecraft** [blrchen/AzureSpeed#79]
Our latency regularly peaks near 2000 ms for many seconds at a time, multiple times in the graph window 45 sec, thus not displaying on the scroling graph . We need the ability to adjust the graph scale to 0-2000 to show our peaks.

![Azure Speed](https://user-images.githubusercontent.com/12091402/65152535-2821d980-d9f6-11e9-8be7-7a659a38a6cc.png)

**Comment by blrchen** [comment]
@softwarecraft Thanks for raising this up and sorry for a long delay from my side. Y asixs range is hard coded to be [0,500]. This has been fixed as part of frontend code angular app re-written.
