### ISSUE TITLE
Adding Norway

### ISSUE THREAD

**Issue by blrchen** [blrchen/AzureSpeed#82]
From twitter by @StanZhelyazkov
any chance of adding Norway to https://azurespeed.co? Thanks!

**Comment by AndreasPaulsson** [comment]
I (a Swede) would also like this. Both Norway West and Norway East.
From Sweden, the lowest latency we can get is ~35 ms to West Europe but I have my hopes set on Norway East.

**Comment by fracol** [comment]
@AzureSupport (on Twitter) also acknowledged a similar request like this from the user @antonioabalos  - Tweet can he found [here](https://twitter.com/antonioabalos/status/1219881613716283392)

**Comment by AndreasPaulsson** [comment]
I realized that this may not be possible at the moment since the Norway regions may not have all the services that are needed for http://www.azurespeed.com/ to make those measurements.

**Comment by blrchen** [comment]
Sorry for a long delay in my side. I just added Norway regions today, thanks again for raising this up.
